### ISSUE TITLE
.OnPressed Error

### ISSUE THREAD

**Issue by RaphBAFR74** [Beckhoff-USA-Community/TcHmiCncControls#1]
Hello BAUS team

Nice development !
i have a problem with TChmi 1.12 & tc3 4024.59 with a setPath 

HmiFramework.js:741 [2024-09-06T13:59:02.444Z][Error] [Source=Framework, Module=TcHmi.System.TriggerManager, Event=TcHmiButton_4.onPressed, ObjectType=ControlApiFunction] Code: 4/0x4, Message: E_EXCEPTION
  Reason: An uncaught exception occurred in the control function of GCodePathRenderer.setPath
  Exception: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
  Domain: TcHmi.System.TriggerManager
Exception: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at GCodePathInterpreter.js:35:33
    at Array.reduce (<anonymous>)
    at GCodePathInterpreter.Trace (GCodePathInterpreter.js:34:36)
    at GCodePathRenderer.__renderPath (GCodePathRenderer.js:263:47)
    at GCodePathRenderer.setPath (GCodePathRenderer.js:466:30)
    at Object.success (TcHmiFramework.js:2818:441789)
    at Object.success (TcHmiFramework.js:2818:436780)
    at Symbol.<anonymous> (TcHmiFramework.js:2818:434557)
    at TcHmi.Callback.callSafeEx (TcHmiFramework.js:391:118)
    at Symbol.<anonymous> (TcHmiFramework.js:1972:309)
L

My text on Editor :
![image](https://github.com/user-attachments/assets/3e7393b3-df75-4c6a-a30c-e586c36e121f)

Action button :
![image](https://github.com/user-attachments/assets/e9b517af-4073-448f-acf7-7c193d39501e)

Do you have an idea?
Thanks
Raph From BAFR

**Comment by bstiffler582** [comment]
I will try to reproduce. I believe it is being thrown because there are no valid gcodes present in the editor.

**Comment by bstiffler582** [comment]
Thank you! This will no longer throw an exception with the latest build. You do still need to provide at least one valid G code in the editor for anything to render 🙂.

[39abd8](https://github.com/Beckhoff-USA-Community/TcHmiCncControls/commit/39abd87b710ce6871c43d4c04e9eb66db36b5f4c)
